name: End-to-end tests
on: 
  # Trigger workflow on any push to any branch
  push:
  # Trigger workflow on scheduled basis
  schedule:
    - cron: '30 2 * * 6' # Run every Saturday at 2:30 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # browser: chrome
          # headed: false
          # spec: cypress/e2e/spec1.cy.js
          command: npm run test:smoke

      - name: Artifacts
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: Cypress Reports
          path: cypress/reports/html/index.html
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: cypress/reports/html